name: Ci
on: 
  push:
    branches: 
      - master
    paths:
      - "**.js"

jobs:
  build:
    runs-on: ${{matrix.os}}
    strategy: 
      matrix:
        node_version: ['8','10','12']
        os: [ubuntu-latest, windows-latest, macOS-latest]
    outputs: 
      output1: ${{ steps.step1.outputs.teste }}
      output2: ${{ steps.step2.outputs.teste }}
    steps:
    - id: 'step1'
      run: echo "::set-output name=teste::Hello"
    - id: 'step2'
      run: echo "::set-output name=teste::World"

  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - run: echo ${{needs.build.outputs.output1}} ${{needs.build.outputs.output2}}
