name: TestCI

on: 
  push:
    branches: 
      - master 
    paths:
      - '**.js'
    
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node_version: ['8', '10', '12']
        os: [ubuntu-latest, windows-latest, macOS-latest]
    outputs: 
      output1: ${{ steps.step1.outputs.test }}
      output2: ${{ steps.step2.outputs.test }}
    steps:
    - id: 'step1'
      run: echo "::set-output name=test::hello"
    - id: 'step2'
      run: echo "::set-output name=test::world"

  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - run: echo ${{needs.build.outputs.output1}} ${{needs.build.outputs.output1}}

 
