name: Ci
on: 
  push:
    branches: 
      - master
    paths:
      - "**.js"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - id: 'step1'
      run: echo Hello World!
    - id: 'step2'
      run: echo Hoje é terça-feira

  test:
    runs-on: ubuntu-latest
    needs: build 
    steps:
    - run: Estamos em 2020
