name: dockerpush
on:
  push:
    branches: [ master ]
jobs:
  docker_push:
    runs-on: ubuntu-latest
    steps:
      - uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: critzel/test
          tags: latest