name: Getting Started
on: 
  push:
    branches: 
      - master


jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      output1: ${{steps.step1.outputs.test}}
      output2: ${{steps.step2.outputs.test}}
    steps:
      - id: "step1"
        run: echo "::set-output name=test::Hello"
      - id: "step2"
        run: echo "::set-output name=test::World"
  test:
   runs-on: ubuntu-latest
   needs: build
   steps:
    - run: echo ${{needs.build.outputs.output1}} ${{needs.build.outputs.output2}} 