# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      output1: ${{steps.step1.outputs.teste}}
      output2: ${{steps.step2.outputs.teste}}
    steps:
      - id: 'step1'
        run: echo "::set-output name=teste::Hello"
      - id: 'step2'
        run: echo "::set-output name=teste::World"
    
  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: 'step'
        run: echo ${{needs.build.outputs.output1}} ${{needs.build.outputs.output2}}