name: Convert_Wiki

on: [ gollum ]

jobs:
  convert:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Checkout & merge submodules
      run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git submodule update --remote --merge
    - name: Push to master
      uses: ad-m/github-push-action@master
      with:
        repository: ${{github.repository}}    
        github_token: ${{ secrets.GITHUB_TOKEN }}
     


