name: Wiki CI

on: 
  push:
    paths:
      - "*.md"

jobs:
  Wiki2HTML:
    runs-on: ubuntu-latest
    steps:
      - name: Instala pandoc
        run: "sudo apt install pandoc"
      - uses: actions/checkout@v2
      - name: Cria wiki.html 
        run: |
          find teste/md -type f -name "*.md" -exec iconv -f iso-8859-1 -t utf-8 "{}" -o "{}.UTF8" \;
          find teste/md -type f -name "*.UTF8" -execdir pandoc "{}" -s -o  "../html/{}.html" \;
          mv **/*.html docs/html
          rm docs/md/*.UTF8
          cd docs/html
          sudo apt install rename
          rename -f 's/.md.UTF8.html/.html/' *   
      - name: Commit wiki.html
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git diff-index --quiet HEAD || git commit -m "Envia Wiki.html"
      - name: Push wiki.html
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
