name: Wiki CI

on: [ push ]

jobs:
  Publish_Wiki:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Upload Documentation to Wiki
      uses: SwiftDocOrg/github-wiki-publish-action@v1
      with:
        path: "Documentação"
      env:
        GH_PERSONAL_ACCESS_TOKEN: ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}

  Wiki2HTML:
    runs-on: ubuntu-18.04
    steps:
      - run: echo "foo" > input.txt  # create an example file
      - uses: docker://pandoc/core:2.9
        with:
          args: |
            --output=index.html
            input.txt
      - run: "cat input.txt"
        
