name: Wiki CI

on: [ push ]

jobs:
  Publish_Wiki:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Upload documentation to wiki
      uses: SwiftDocOrg/github-wiki-publish-action@v1
      with:
        path: "Documentação"
      env:
        GH_PERSONAL_ACCESS_TOKEN: ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}






Wiki2HTML:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - id: action 
        uses: docker://pandoc/core:2.9
        with:
          args: |  # allows you to break string into multiple lines
            --output=index.html
            Documentação.TesteAction
      - name: Commit wiki.html
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git commit -m "Envia Wiki.html"
      - name: Push wiki.html
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}

