name: Wiki CI

on: 
  push:
    paths:
      - "*.md"

jobs:
  Wiki2HTML:
    runs-on: ubuntu-latest
    steps:
      - name: Instala pandoc
        run: "sudo apt install pandoc"
      - uses: actions/checkout@v2
      - name: Cria arquivos html 
        run: |
          cp -R teste/md/* teste/html
          find teste/html -type f -name "*.md" -exec iconv -f iso-8859-1 -t utf-8 "{}" -o "{}.UTF8" \; -exec rm "{}" \;
          find teste/html -type f -name "*.UTF8" -exec pandoc "{}" -s -o  "{}.html" \; -exec rm "{}" \;
          sudo apt install rename
          find teste/html -name "*.UTF8.html" -exec rename -v 's/\.md.UTF8.html$/\.html/i' {} \;
      - name: Commit wiki.html
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git diff-index --quiet HEAD || git commit -m "Gera arquivos html"
      - name: Push wiki.html
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
