name: Convert_Wiki

on: [ gollum ]

jobs:
  convert:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          repository: ${{github.repository}}.wiki

      - name: check wiki repo content
        run: |
          ls -al
      - name: Commit files
        run: |
          git config --local user.email "cassioritzel@gmail.com"
          git config --local user.name "CRitzel"
          git add .
          git commit -m "Add changes"
      - name: Push changes to wiki repo
        uses: ad-m/github-push-action@master
        with:
          repository: ${{github.repository}}.wiki    # specify the wiki repo and push the update.
          github_token: ${{ secrets.GITHUB_TOKEN }}
