name: Test

on:
  pull_request:
    branches:
    - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkouts repository
      uses: actions/checkout@v2

    - name: Set up Node
      uses: actions/setup-node@v2-beta
      with:
        node-version: '12'
        
    - name: Install dependencies
      run: yarn

    - name: Test
      run: yarn test --coverage
   
    - name: Check linting
      run: yarn lint

    - name: Check commit message
      uses: wagoid/commitlint-github-action@v1